### ISSUE TITLE
[zkDOOM] cannot build on mac m1pro 

### ISSUE THREAD

**Issue by nagatoism** [risc0/demos#17]
have both  MacOS deps llvm and imagemagick installed 

build failed at 

doom: Starting build for riscv32im-risc0-zkvm-elf risc0-circuit-rv32im-sys(build), clap_derive, puredoom-rs(build), image, risc0-circuit-recursion-sys(build), methods(build), protobu...
doom: error: package `home v0.5.9` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.69.0-dev
doom: Either upgrade to rustc 1.70.0 or newer, or use
doom: cargo update home@0.5.9 --precise ver
doom: where `ver` is the latest version of `home` supporting rustc 1.69.0-dev

toolchain:
active toolchain
----------------

stable-aarch64-apple-darwin (overridden by '/Users/xxxx/github/risc0/demos/zkdoom/rust-toolchain.toml')
rustc 1.76.0 (07dca489a 2024-02-04)

**Comment by mothran** [comment]
Interesting, I just tested it again and it works (on linux) but lets double check your risc0 toolchain version:

https://github.com/risc0/risc0/blob/main/risc0/cargo-risczero/README.md#install

Specially:

`rustup toolchain list --verbose | grep risc0`

I have: `<snip>/x86_64-unknown-linux-gnu_v2024-01-31.1/rust`

If yours is older then run: `cargo risczero install`

**Comment by nagatoism** [comment]
Hi chicken_lover in discord told me to downgrade 
the home crate from 0.5.9 to 0.5.5 to fix this.
The command is 
`cargo update --package home@0.5.9 --precise 0.5.5
`
After the downgrade, the error is gone. My suggestion is too add this to the doc and close this issue.

**Comment by nagatoism** [comment]
after 
`rustup toolchain list --verbose | grep risc0`

risc0	/Users/wangyao/Library/Application Support/cargo-risczero/toolchains/aarch64-apple-darwin_test-release-2/rust


I am still having some protobuf compile issue after the home downgrade.

**Comment by mothran** [comment]
Yeah I think that is one of our older toolchains, I would recommend running: `cargo risczero install` to update.
