### ISSUE TITLE
Improve findability of related resources

### ISSUE THREAD

**Issue by pdg744** [risc0/demos#7]
I'd like to make sure that users who find themselves in this repo have clear paths to learn more. 

A few specific ideas to improve this: 
- [x] Add pointer from Bonsai Pay readme to Bonsai Pay article
- [x] Add pointer from `demos` readme to https://risczero.com and/or dev.risczero.com 
- [x] Add directory readmes for `/contracts` and `/methods` to clarify program architecture (see https://github.com/risc0/bonsai-foundry-template/tree/main/contracts for reference)

**Comment by pdg744** [comment]
Relatedly: it may make sense to consolidate this list of places we put examples/demos:
- risc0/risc0/examples
- risc0/risc0/bonsai/examples
- risc0/demos
- risc0/zeth

**Comment by hmrtn** [comment]
Is a an example a demo? I imagine a demo to be something more user-friendly, and generally less developer focused. Open to thoughts on this.

**Comment by flaub** [comment]
I think we should keep examples and demos separate. Examples are meant to be simple, to show the capabilities of the zkvm. A demo is meant to be an app.
